export const contentObj = {
  pl: {
    start: {
      heading:
        "to aplikacja do kontrolowania wydatków i serwisów swojego auta! Oferuje wiele zalet, które sprawią, że zarządzanie finansami i konserwacją samochodu będzie łatwiejsze i bardziej przejrzyste.",
      listHeading: "Główne zalety tej aplikacji to:",
      listElements: [
        "Przejrzystość: aplikacja została zaprojektowana w taki sposób, aby zapewnić przejrzysty i intuicyjny interfejs użytkownika. Dzięki temu łatwo będzie poruszać się po różnych sekcjach i znaleźć potrzebne      informacje.",
        "Dostęp z poziomu strony internetowej: aplikacja jest dostępna z        poziomu przeglądarki internetowej. Oznacza to, że możesz zalogować        się na swoje konto i uzyskać dostęp do swoich danych z dowolnego        urządzenia, które ma dostęp do internetu. Niezależnie od tego, czy        używasz komputera, smartfona czy tabletu, zawsze będziesz mieć        dostęp do swoich informacji.",
        "Eksport danych do tabeli Excel: W aplikacji możesz eksportować swoje dane finansowe i informacje dotyczące serwisów samochodu do plików Excel. Dzięki temu będziesz mógł łatwo analizować i przetwarzać te dane w formacie, który najbardziej Ci odpowiada. Dzięki tej aplikacji będziesz mógł śledzić swoje wydatki związane z samochodem, kontrolować koszty serwisów i utrzymania, a także analizować swoje wydatki w bardziej rozbudowany sposób. Niezależnie od tego, czy jesteś właścicielem jednego samochodu czy floty pojazdów, poniższa aplikacja pomoże Ci utrzymać kontrolę nad finansami i serwisam swojego auta.",
      ],
      ending:
        "Zapraszam do wypróbowania aplikacji i cieszenia się korzyściami, jakie ona oferuje!",
      testingAlert: "Aplikacja w trakcie testów - eksportuj dane do xls!",
    },

    about: {
      title: "O projekcie",
      navTitle: "Projekt",
      paragraph:
        "Aplikacja do śledzenia serwisów Twojego pojazdu. Pozwala w prosty sposób być na bieżąco z naprawami oraz wydatkami.",
    },
    myCars: {
      title: "Garaż",
      addButton: "Dodaj pojazd",
      closeButton: "Zamknij",
      brand: "Marka",
      model: "Model",
      year: "Rocznik",
      mileage: "Przebieg",
      img: "Wklej zdjęcie",
      plates: "nr rejestracyjny",
      submit: "Dodaj",
      currentMileage: "Aktualny przebieg",
      submit: "dodaj",
      update: "zaktualizuj",
    },
    services: {
      heading: "Serwisy",
      title: "nazwa",
      date: "data",
      desc: "opis",
      mileage: "przebieg",
      price: "cena",
      addButton: "dodaj",
      categories: {
        maintenance: "serwis",
        fix: "naprawa",
        aesthetics: "estetyka",
      },
      filters: {
        filters: "Filtry",
        fix: "naprawy",
        aesthetics: "estetyka",
        maintenance: "serwisy",
        done: "zrobione",
        todo: "do zrobienia",
      },
    },

    welcome: "Witaj",
    login: "Zaloguj",
    logout: "Wyloguj",
    backToGarage: "wróć do garażu",
    loginPage: {
      title: "Zaloguj się",
      paragraph: "Musisz się zalogować, żeby zobaczyć auta",
      loginCredentials: "Podaj dane logowania",
      email: "email",
      password: "hasło",
      login: "Zaloguj",
      useServices: "lub użyj serwisu",
      useGoogle: "Zaloguj z Google",
      wrongUser: "Nieprawidłowe dane",
    },

    register: {
      title: "Dołącz",
      loginCredentials: "Podaj dane nowego konta",
      email: "Email",
      password: "Hasło",
      confirm: "Potwierdź hasło",
      name: "Imię",
      avatar: "Wklej awatar",
      sign: "Zapisz",
      useGoogle: "lub użyj serwisu:",
      signInGoogle: "Zaloguj z Google",
    },
  },
  en: {
    start: {
      heading:
        "This is an application for managing expenses and services for your car! It offers many advantages that will make managing your finances and car maintenance easier and more transparent.",
      listHeading: "The main advantages of this application are:",
      listElements: [
        "Transparency: The application has been designed to provide a clear and intuitive user interface. This makes it easy to navigate through different sections and find the information you need.",
        "Web access: The application is accessible from a web browser. This means you can log in to your account and access your data from any device that has internet access. Whether you're using a computer, smartphone, or tablet, you will always have access to your information.",
        "Export data to Excel: In the application, you can export your financial data and car service information to Excel files. This allows you to easily analyze and process the data in a format that suits you best. With this application, you can track your car-related expenses, control service and maintenance costs, and analyze your expenses in a more comprehensive way. Whether you own a single car or a fleet of vehicles, this application will help you maintain control over your car's finances and services.",
      ],
      ending: "Try out the application and enjoy the benefits it offers!",
      testingAlert:
        "The application is currently in testing - export your data to xls!",
    },
    about: {
      title: "About",
      navTitle: "About",
      paragraph:
        "A car service app is a mobile application designed to help car owners conveniently manage and maintain their vehicles. It provides a range of features and functionalities to streamline the car servicing process and enhance the overall experience for users.",
    },
    myCars: {
      title: "Garage",
      addButton: "Add car",
      closeButton: "close",
      brand: "Brand",
      model: "Model",
      year: "Year",
      mileage: "Mileage",
      img: "Paste img",
      plates: "Plates",
      submit: "Add",
      currentMileage: "Current mileage",
      submit: "Submit",
      update: "Update",
    },
    services: {
      heading: "Services",
      title: "Title",
      date: "Date",
      desc: "Description",
      mileage: "Mileage",
      price: "Price",
      addButton: "Add",
      categories: {
        maintenance: "Maintenance",
        fix: "Fix",
        aesthetics: "Aesthetics",
      },
      filters: {
        filters: "Filters",
        fix: "fix",
        aesthetics: "aesthetics",
        maintenance: "maintenance",
        done: "done",
        todo: "todo",
      },
    },
    welcome: "Hello",
    login: "Login",
    logout: "Logout",
    backToGarage: "wróć do garażu",
    loginPage: {
      title: "Please log in",
      paragraph: "You need to log in to add and see your cars",
      loginCredentials: "Podaj dane logowania",
      email: "email",
      password: "hasło",
      login: "Zaloguj",
      useServices: "lub użyj serwisu",
      useGoogle: "Zaloguj z Google",
      wrongUser: "Wrong user or password",
    },
    register: {
      title: "Join",
      loginCredentials: "New Account",
      email: "email",
      password: "password",
      confirm: "confirm password",
      name: "name",
      avatar: "paste avatar",
      sign: "sing in",
      useGoogle: "or use:",
      signInGoogle: "Sign in with Google",
    },
  },
};
