export const contentObj = {
  pl: {
    start: {
      heading: "title",
    },
    about: {
      title: "O projekcie",
      paragraph:
        "Aplikacja do śledzenia serwisów Twojego pojazdu. Pozwala w prosty sposób być na bieżąco z naprawami oraz wydatkami.",
    },
    myCars: {
      title: "Garaż",
      addButton: "Dodaj pojazd",
      closeButton: "Zamknij",
      brand: "Marka",
      model: "Model",
      year: "Rocznik",
      mileage: "Przebieg",
      img: "Wklej zdjęcie",
      plates: "nr rejestracyjny",
      submit: "Dodaj",
      currentMileage: "Aktualny przebieg",
      submit: "dodaj",
      update: "zaktualizuj",
    },
    services: {
      heading: "Serwisy",
      title: "nazwa",
      date: "data",
      desc: "opis",
      mileage: "przebieg",
      price: "cena",
      addButton: "dodaj",
    },

    welcome: "Witaj",
    login: "Zaloguj",
    logout: "Wyloguj",
    backToGarage: "wróć do garażu",
    loginPage: {
      title: "Zaloguj się",
      paragraph: "Musisz się zalogować, żeby zobaczyć auta",
      loginCredentials: "Podaj dane logowania",
      email: "email",
      password: "hasło",
      login: "Zaloguj",
      useServices: "lub użyj serwisu",
      useGoogle: "Zaloguj z Google",
      wrongUser: "Nieprawidłowe dane",
    },

    register: {
      title: "Dołącz",
      loginCredentials: "Podaj dane nowego konta",
      email: "email",
      password: "hasło",
      confirm: "potwierdź hasło",
      name: "imię",
      avatar: "wklej awatar",
      sign: "zapisz",
      useGoogle: "lub użyj serwisu:",
      signInGoogle: "Zaloguj z Google",
    },
  },
  en: {
    start: {
      heading: "title",
    },
    about: {
      title: "About",
      paragraph:
        "A car service app is a mobile application designed to help car owners conveniently manage and maintain their vehicles. It provides a range of features and functionalities to streamline the car servicing process and enhance the overall experience for users.",
    },
    myCars: {
      title: "Garage",
      addButton: "add car",
      closeButton: "close",
      brand: "brand",
      model: "model",
      year: "year",
      mileage: "mileage",
      img: "paste img",
      plates: "plates",
      submit: "add",
      currentMileage: "current mileage",
      submit: "submit",
      update: "update",
    },
    services: {
      heading: "services",
      title: "title",
      date: "date",
      desc: "description",
      mileage: "mileage",
      price: "price",
      addButton: "add",
    },
    welcome: "Hello",
    login: "Login",
    logout: "Logout",
    backToGarage: "wróć do garażu",
    loginPage: {
      title: "Please log in",
      paragraph: "You need to log in to add and see your cars",
      loginCredentials: "Podaj dane logowania",
      email: "email",
      password: "hasło",
      login: "Zaloguj",
      useServices: "lub użyj serwisu",
      useGoogle: "Zaloguj z Google",
      wrongUser: "Wrong user or password",
    },
    register: {
      title: "Join",
      loginCredentials: "New Account",
      email: "email",
      password: "password",
      confirm: "confirm password",
      name: "name",
      avatar: "paste avatar",
      sign: "sing in",
      useGoogle: "or use:",
      signInGoogle: "Sign in with Google",
    },
  },
};
